
# Vagrant.configure("2") do |config|
#   # Box à utiliser
#   config.vm.box = "generic/alpine312"

#   # VM 1
#   config.vm.define "jecolmouS" do |jecolmouS|
# 	jecolmouS.vm.hostname = "jecolmouS"
# 	# Definir les ressources obligatoires dans le sujet
# 	jecolmouS.vm.provider "virtualbox" do |vb|
# 		vb.memory = "1024"
# 		vb.cpus = 1
# 	end

#     	# Configuration réseau
# 	jecolmouS.vm.network "private_network", ip: "192.168.56.110"
    	
# 	jecolmouS.vm.synced_folder "./confs", "/confs", type: "virtualbox"
# 	# Forcer IPv4 et désactiver IPv6 dans la VM
# 	jecolmouS.vm.provision "shell", inline: <<-SHELL
# 		# Installer curl si besoin
#       		sudo apk add --no-cache curl

#       		# Installer k3s en mode serveur
#       		curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-iface eth1" sh -

#       		# Attendre que le token soit créé
#       		NODE_TOKEN="/var/lib/rancher/k3s/server/node-token"
#       		while [ ! -e ${NODE_TOKEN} ]; do
#         		sleep 2
#       		done

#       		# Copier le token et le kubeconfig dans le dossier partagé
#       		sudo cp ${NODE_TOKEN} /confs/node-token
#       		sudo cp /etc/rancher/k3s/k3s.yaml /k3s.yaml
#       		sudo chmod 644 /node-token /k3s.yaml
# 		SHELL
# 	end

#   # VM 2
#   config.vm.define "jecolmouSW" do |jecolmouSW|
# 	jecolmouSW.vm.hostname = "jecolmouSW"

# 	# Definir les ressources obligatoires dans le sujet
#         jecolmouSW.vm.provider "virtualbox" do |vb|
#                 vb.memory = "1024"
#                 vb.cpus = 1
#         end

#     	# Configuration réseau
# 	jecolmouSW.vm.network "private_network", ip: "192.168.56.111"
	
# 	# Forcer IPv4 et désactiver IPv6 dans la VM
# 	jecolmouSW.vm.provision "shell", inline: <<-SHELL
# 		# Installer curl si besoin
#       		sudo apk add --no-cache curl

#       		# Récupérer le token depuis le dossier partagé
#       		K3S_TOKEN=$(sudo cat /confs/node-token)

#       		# Installer k3s en mode agent et se connecter au master
#       		curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$K3S_TOKEN INSTALL_K3S_EXEC="--flannel-iface eth1" sh -
# 		SHELL
# 	end
# end


Vagrant.configure("2") do |config|

  # Box à utiliser
  config.vm.box = "ubuntu/jammy64"
 

  # VM 1 - Server
  config.vm.define "jecolmouS" do |jecolmouS|
    jecolmouS.vm.hostname = "jecolmouS"

    # Definir les ressources obligatoires dans le sujet
    jecolmouS.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
	  vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    # Configuration réseau
    jecolmouS.vm.network "private_network", ip: "192.168.56.110"

	# Configuration systeme et prerequis
	jecolmouS.vm.provision "shell", inline: <<-SHELL
		set -e

    # Forcer IPv4 et désactiver IPv6 dans la VM
		echo "net.ipv6.conf.all.disable_ipv6 = 1" | sudo tee -a /etc/sysctl.conf
      	echo "net.ipv6.conf.default.disable_ipv6 = 1" | sudo tee -a /etc/sysctl.conf
      	sudo sysctl -p
      	
		# Forcer apt à utiliser IPv4
      	echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4

		#MAJ et install des paquets de base
		export DEBIAN_FRONTEND=noninteractive
		sudo apt-get update -o Acquire::ForceIPV4=true
		sudo apt-get install -y curl apt-transport-https ca-certificates

		#Desactiver le swap, requis par K3s
		sudo swapoff -a
		sudo sed -i '/ swap / s/^/#/' /etc/fstab

		echo "----------Prerequis installes ok"
	SHELL

    # Installer k3s en mode controlleur
    jecolmouS.vm.provision "shell", inline: <<-SHELL
		set -e
    	
		echo "---------- On va resoudre cette ip"
		IFACE=$(ip -4 addr show | grep "192.168.56.110" | awk '{print $NF}')

		if [ -z "$IFACE" ]; then
			echo "----------ERREUR: impossible de trouver l'interface du reseau"
			ip addr show
			exit 1
		fi

		echo "----------interface detectee : $IFACE"

		echo "----------Installation de K3s en mode controller = server..."
     
		curl -sfL https://get.k3s.io | sh -s - server \
			--node-ip=192.168.56.110 \
			--flannel-iface=$IFACE \
			--write-kubeconfig-mode=644 \
			--disable=traefik \

      	# Attendre que K3s soit complètement prêt
      	echo "----------Attente du démarrage de K3s server..."
		sleep 10

		#Verifier le statut
		if ! sudo systemctl is-active --quiet k3s; then
			echo "ERREUR: k3s n'a pas demarre correctement"
			sudo journalctl -u k3s.service -n 50 --no-pager
			exit 1
		fi

		# Attendre que kubectl soit fonctionnel
		attempt=0
		max_attempts=30
		until sudo k3s kubectl get nodes 2>/dev/null || [ $attempt -eq $max_attempts ]; do
			echo "----------Kubectl pas encore prêt, en attente...($attempts/$max_attempts)"
			sleep 2
			attempt=$((attempt + 1))
		done

		if [ $attempt -eq $max_attempts ]; then
			echo "----------ERREUR: kubectl ne repond pas"
			exit 1
		fi

		# Lien symbolique pour kubectl
		sudo ln -sf /usr/local/bin/k3s /usr/local/bin/kubectl

		# Copier le token
		sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/k3s_token
      	sudo chmod 644 /vagrant/k3s_token
     

		echo "----------*** OK *** k3s server installe avec SUCCES"
		sudo kubectl get nodes
    SHELL
  end

  # VM 2 - ServerWorker
  config.vm.define "jecolmouSW" do |jecolmouSW|
    jecolmouSW.vm.hostname = "jecolmouSW"

    # Definir les ressources obligatoires dans le sujet
    jecolmouSW.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
	  vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    # Configuration réseau
    jecolmouSW.vm.network "private_network", ip: "192.168.56.111"

	# Configurqtion systeme et prerequis
	jecolmouSW.vm.provision "shell", inline: <<-SHELL
		set -e

    	# Forcer IPv4 et désactiver IPv6 dans la VM
      	echo "net.ipv6.conf.all.disable_ipv6 = 1" | sudo tee -a /etc/sysctl.conf
      	echo "net.ipv6.conf.default.disable_ipv6 = 1" | sudo tee -a /etc/sysctl.conf
      	sudo sysctl -p

      	# Forcer apt à utiliser IPv4
      	echo '----------Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4
		# MAJ des installations
		export DEBIAN_FRONTEND=noninteractive
		sudo apt-get update -o Acquire::ForceIPV4=true
		sudo apt-get install -y curl apt-transport-https ca-certificates

		#Desactiver le swap, requis par K3s
		sudo swapoff -a
		sudo sed -i '/ swap / s/^/#/' /etc/fstab

		echo "----------Prerequis installes ok"
	SHELL

    # Installer k3s en mode agent
    jecolmouSW.vm.provision "shell", inline: <<-SHELL
		set -e

		# Attendre le token
		echo "----------attente du token de jecolmouS"
		attempt=0
		until [ -f /vagrant/k3s_token ] || [ $attempt -eq 60 ]; do
			sleep 2
			attempt=$((attempt + 1))
		done

		if [ ! -f /vagrant/k3s_token ]; then
			echo "----------ERREUR: Token nooooo dispo"
			exit 1
		fi

		# Verifier la connection avec le serveur
		echo "----------Verfication de la connection au serveur..."
		attempt=0
		until nc -z -w5 192.168.56.110 6443 || [ $attempt -eq 30 ]; do
			echo "Serveur pas encore accessible...($attempt/30)"
			sleep 5
			attempt=$((attempt + 1))
		done

		if [ $attempt -eq 30 ]; then
			echo "----------ERREUR: Depuis l'agent = serveur inaccessible"
			exit 1
		fi

		echo "---------- On va resoudre cette ip"
		IFACE=$(ip -4 addr show | grep "192.168.56.111" | awk '{print $NF}')

		if [ -z "$IFACE" ]; then
			echo "----------ERREUR: impossible de trouver l'interface du reseau"
			ip addr show
			exit 1
		fi

		echo "----------interface detectee : $IFACE"

	    # Installer l'agent K3s
		echo "----------Installation de k3s agent"
		K3S_TOKEN=$(cat /vagrant/k3s_token)
		curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 \
			K3S_TOKEN=$K3S_TOKEN sh -s - agent \
			--node-ip=192.168.56.111 \
			--flannel-iface=$IFACE
		
		# Attendre que l'agent soit good
		sleep 5
		if ! sudo systemctl is-active --quiet k3s-agent; then
			echo "----------ERREUR: K3s agent n'a pas demarre"
			sudo journalctl -u k3s-agent.service -n 50 --no-pager
			exit 1
		fi

		sudo ln -sf /usr/local/bin/k3s /usr/local/bin/kubectl
		echo "----------*** OK *** K3s agent SUCCES"
    SHELL
  end
end
